export const description = [
    /*BOMBA-AGUA*/
    {
        id: "bomba-1",
        dataProducto: "agua",
        categoria: "bomba",
        nombre: "Bomba de agua",
        img: "./img/bomba/bombaAgua1.1.jpg",
        imgHover: "./img/bomba/bombaAgua1.2.jpg",
        repuesto: "para motor 14 litros DDEC 4",
        precio: 0,
        descripcion: `para motor 14 litros DDEC 4`,

    },
    {
        id: "bomba-2",
        dataProducto: "agua",
        categoria: "bomba",
        nombre: "Bomba de agua",
        img: "./img/bomba/bombaAgua2.1.jpg",
        imgHover: "./img/bomba/bombaAgua2.2.jpg",
        repuesto: "para motor 14 litros DDEC 5",
        precio: 0,
        descripcion: `para motor 14 litros DDEC 5`,

    },
    {
        id: "bomba-3",
        dataProducto: "agua",
        categoria: "bomba",
        nombre: "Bomba de agua",
        img: "./img/bomba/bombaAgua3.1.jpg",
        imgHover: "./img/bomba/bombaAgua3.2.jpg",
        repuesto: "para motor 14litros DDEC 6",
        precio: 0,
        descripcion: `para motor 14litros DDEC 6`,

    },
    {
        id: "bomba-4",
        dataProducto: "agua",
        categoria: "bomba",
        nombre: "Bomba de agua",
        img: "./img/bomba/bombaAgua4.1.jpg",
        imgHover: "./img/bomba/bombaAgua4.2.jpg",
        repuesto: "para DD13 marca TDP",
        precio: 0,
        descripcion: `para DD13 marca TDP`,

    },
    //BOMBA-ACEITE
    {
        id: "bomba-5",
        dataProducto: "aceite",
        categoria: "bomba",
        nombre: "Bomba de aceite",
        img: "./img/bomba/bombaAceite1.1.jpg",
        imgHover: "./img/bomba/bombaAceite1.2.jpg",
        repuesto: "para motor Detroit 12.7 DDEC 3",
        precio: 0,
        descripcion: `para motor Detroit 12.7 DDEC 3`,

    },
    {
        id: "bomba-6",
        dataProducto: "aceite",
        categoria: "bomba",
        nombre: "Bomba de aceite",
        img: "./img/bomba/bombaAceite2.1.jpg",
        imgHover: "./img/bomba/bombaAceite2.2.jpg",
        repuesto: "para motor Detroit 12.7 DDEC 4",
        precio: 0,
        descripcion: `para motor Detroit 12.7 DDEC 3`,

    },
    {
        id: "bomba-7",
        dataProducto: "aceite",
        categoria: "bomba",
        nombre: "Bomba de aceite",
        img: "./img/bomba/bombaAceite3.1.jpg",
        imgHover: "./img/bomba/bombaAceite3.2.jpg",
        repuesto: "para DD15 marca TDP",
        precio: 0,
        descripcion: `para motor Detroit 12.7 DDEC 3`,

    },
    {
        id: "bomba-8",
        dataProducto: "aceite",
        categoria: "bomba",
        nombre: "Bomba de aceite",
        img: "./img/bomba/bombaAceite4.1.jpg",
        imgHover: "./img/bomba/bombaAceite4.2.jpg",
        precio: 0,
        repuesto: "para motor Detroit DD15",
        descripcion: `para motor Detroit 12.7 DDEC 3`,

    },
    {
        id: "bomba-9",
        dataProducto: "aceite",
        categoria: "bomba",
        nombre: "Bomba de aceite",
        img: "./img/bomba/bombaAceite5.1.jpg",
        imgHover: "./img/bomba/bombaAceite5.2.jpg",
        precio: 0,
        repuesto: "para motor DD15, DD13, DD16 original Detroit",
        descripcion: `para motor Detroit 12.7 DDEC 3`,

    },
    {
        id: "bomba-10",
        dataProducto: "hidraulica",
        categoria: "bomba",
        nombre: "Bomba hidraulica",
        img: "./img/bomba/bombaHidraulica1.1.jpg",
        imgHover: "./img/bomba/bombaHidraulica1.2.jpg",
        precio: 0,
        repuesto: "DD16 hidrodinamica marca TDP",
        descripcion: ``,

    },
    {
        id: "bomba-11",
        dataProducto: "hidraulica",
        categoria: "bomba",
        nombre: "Bomba hidraulica",
        img: "./img/bomba/bombaHidraulica2.1.jpg",
        imgHover: "./img/bomba/bombaHidraulica2.2.jpg",
        precio: 0,
        repuesto: "para motor OM460",
        descripcion: ``,

    },
    {
        id: "bomba-12",
        dataProducto: "hidraulica",
        categoria: "bomba",
        nombre: "Bomba hidraulica",
        img: "./img/bomba/bombaHidraulica3.1.jpg",
        imgHover: "./img/bomba/bombaHidraulica3.2.jpg",
        precio: 0,
        repuesto: "para motor OM460 original TRW",
        descripcion: ``,

    },
    {
        id: "bomba-13",
        dataProducto: "hidraulica",
        categoria: "bomba",
        nombre: "Bomba hidraulica",
        img: "./img/bomba/bombaHidraulica4.1.jpg",
        imgHover: "./img/bomba/bombaHidraulica4.2.jpg",
        precio: 0,
        repuesto: "",
        descripcion: `marca Bosch para motor 14 litros`,

    },
    {
        id: "bomba-14",
        dataProducto: "transferencia",
        categoria: "bomba",
        nombre: "Bomba de transferencia",
        img: "./img/bomba/bombatransferencia5.1.jpg",
        imgHover: "./img/bomba/bombatransferencia5.2.jpg",
        precio: 0,
        repuesto: "para motor Detroit 14litros 12.7",
        descripcion: ``,

    },
     {
        id: "bomba-15",
        dataProducto: "transferencia",
        categoria: "bomba",
        nombre: "Bomba de transferencia",
        img: "./img/bomba/bombatransferencia6.1.jpg",
        imgHover: "./img/bomba/bombatransferencia6.2.jpg",
        precio: 0,
        repuesto: "para combustible aplica motor 12.7 DDCE 3, DDEC 4, marca TDP",
        descripcion: ``,

    },
    {
        id: "bomba-16",
        dataProducto: "transferencia",
        categoria: "bomba",
        nombre: "Bomba de transferencia",
        img: "./img/bomba/bombatransferencia7.1.jpg",
        imgHover: "./img/bomba/bombatransferencia7.2.jpg",
        precio: 0,
        repuesto: "para combustible aplica motor 12.7 DDCE 3, DDEC 4, marca TDP",
        descripcion: ``,

    },
    {
        id: "bomba-17",
        dataProducto: "transferencia",
        categoria: "bomba",
        nombre: "Bomba de transferencia",
        img: "./img/bomba/bombatransferencia8.1.jpg",
        imgHover: "./img/bomba/bombatransferencia8.2.jpg",
        precio: 0,
        repuesto: "para combustible aplica motor 12.7 DDCE 3, DDEC 4, marca TDP",
        descripcion: ``,

    },
    {
        id: "bomba-18",
        dataProducto: "auxiliar",
        categoria: "bomba",
        nombre: "Bomba auxiliar",
        img: "./img/bomba/bombaAuxiliar1.1.jpg",
        imgHover: "./img/bomba/bombaAuxiliar1.2.jpg",
        precio: 0,
        repuesto: "de clutch para cascadia marca Wabco",
        descripcion: ``,

    },
    {
        id: "bomba-19",
        dataProducto: "auxiliar",
        categoria: "bomba",
        nombre: "Bomba auxiliar",
        img: "./img/bomba/bombaAuxiliar2.1.jpg",
        imgHover: "./img/bomba/bombaAuxiliar2.2.jpg",
        precio: 0,
        repuesto: "para cascadia marca TDP",
        descripcion: ``,

    },
    {
        id: "bomba-20",
        dataProducto: "auxiliar",
        categoria: "bomba",
        nombre: "Bomba auxiliar",
        img: "./img/bomba/bombaAuxiliar3.1.jpg",
        imgHover: "./img/bomba/bombaAuxiliar3.2.jpg",
        precio: 0,
        repuesto: "para Clutche para cascadia marca TDP",
        descripcion: ``,

    },
    {
        id: "bomba-21",
        dataProducto: "central",
        categoria: "bomba",
        nombre: "Bomba central",
        img: "./img/bomba/bombacentral1.1.jpg",
        imgHover: "./img/bomba/bombacentral1.2.jpg",
        precio: 0,
        repuesto: "para Clutche para cascadia marca TDP",
        descripcion: ``,

    },
    {
        id: "bomba-22",
        dataProducto: "pedal",
        categoria: "bomba",
        nombre: "Pedal para bomba",
        img: "./img/bomba/pedal1.1.jpg",
        imgHover: "./img/bomba/pedal1.2.jpg",
        precio: 0,
        repuesto: "para Clutch de cascadia marca TDP",
        descripcion: ``,

    },
    {
        id: "bomba-23",
        dataProducto: "pedal",
        categoria: "bomba",
        nombre: "Pedal con bomba",
        img: "./img/bomba/pedal2.1.jpg",
        imgHover: "./img/bomba/pedal2.2.jpg",
        precio: 0,
        repuesto: "central Clutche para Cascadia",
        descripcion: ``,

    },
    {
        id: "bomba-24",
        dataProducto: "secador",
        categoria: "bomba",
        nombre: "Secador de aire",
        img: "./img/bomba/secador1.1.jpg",
        imgHover: "./img/bomba/secador1.2.jpg",
        precio: 0,
        repuesto: "para cascadia marca Wabco", 
        descripcion: ``,
    },

    //-----------   ELECTRICO -------
    {
        id: "inyector-1",
        dataProducto: "inyector",
        categoria: "inyectores",
        nombre: "Inyector",
        img: "img/inyectores/inyectorDetroitDDEC5-1.webp",
        imgHover: "img/inyectores/inyectorDetroitDDEC5-2.webp",
        precio: 0,
        repuesto: "para motor Detroit 14litros DDEC 5 marca TDP", 
        descripcion: ``,
    },
    {
        id: "inyector-2",
        dataProducto: "inyector",
        categoria: "inyectores",
        nombre: "Inyector",
        img: "img/inyectores/inyectorDDEC6Delphi-1.jpg",
        imgHover: "img/inyectores/inyectorDDEC6Delphi-2.jpg",
        precio: 0,
        repuesto: "para motor 14litros DDEC 6 marca Delphi", 
        descripcion: ``,
    },
    {
        id: "inyector-3",
        dataProducto: "Inyector",
        categoria: "Inyectores",
        nombre: "Inyector",
        img: "img/inyectores/inyectorDetroitTDP-1.jpg",
        imgHover: "img/inyectores/inyectorDetroitTDP-2.jpg",
        precio: 0,
        repuesto: "para motor Detroit 12,7 marca TDP", 
        descripcion: ``,
    },
    //--------- FILTROS -----
    {
        id: "filtro-1",
        dataProducto: "filtros",
        categoria: "filtros",
        nombre: "Filtro",
        img: "img/filtro/Filtros originales1.jpg",
        imgHover: "img/filtro/filtros.jpg",
        precio: 0,
        repuesto: "filtro", 
        descripcion: ``,
    },
    {
        id: "filtros-2",
        dataProducto: "filtros",
        categoria: "filtros",
        nombre: "Filtro",
        img: "img/filtro/Filtros originales1.jpg",
        imgHover: "img/filtro/filtros.jpg",
        precio: 0,
        repuesto: "filtro", 
        descripcion: ``,
    },
    {
        id: "filtros-3",
        dataProducto: "filtro",
        categoria: "filtros",
        nombre: "Filtro",
        img: "img/filtro/Filtros originales1.jpg",
        imgHover: "img/filtro/filtros.jpg",
        precio: 0,
        repuesto: "fitro", 
        descripcion: ``,
    },
    {
        id: "filtros-4",
        dataProducto: "filtro",
        categoria: "filtros",
        nombre: "Filtro",
        img: "img/filtro/Filtros originales1.jpg",
        imgHover: "img/filtro/filtros.jpg",
        precio: 0,
        repuesto: "fitro", 
        descripcion: ``,
    },
    {
        id: "filtros-5",
        dataProducto: "filtro",
        categoria: "filtros",
        nombre: "Filtro",
        img: "img/filtro/Filtros originales1.jpg",
        imgHover: "img/filtro/filtros.jpg",
        precio: 0,
        repuesto: "fitro", 
        descripcion: ``,
    },
    {
        id: "filtros-6",
        dataProducto: "filtro",
        categoria: "filtros",
        nombre: "Filtro",
        img: "img/filtro/Filtros originales1.jpg",
        imgHover: "img/filtro/filtros.jpg",
        precio: 0,
        repuesto: "fitro", 
        descripcion: ``,
    },
    //-------   HIDRAULICO
    {
        id: "compresor-1",
        dataProducto: "compresor",
        categoria: "compresor",
        nombre: "Compresor",
        img: "img/compresores/Compresor para motor 14 litros DDEC 51.jpg",
        imgHover: "img/compresores/Compresor para motor 14 litros DDEC 52.jpg",
        precio: 0,
        repuesto: "para motor 14 litros DDEC 5 marca Vaden", 
        descripcion: ``,
    },
    {
        id: "compresor-2",
        dataProducto: "compresor",
        categoria: "compresor",
        nombre: "Compresor de AC",
        img: "img/compresores/Compresor de AC1.avif",
        imgHover: "img/compresores/Compresor de AC2.avif",
        precio: 0,
        repuesto: "para cascadia", 
        descripcion: ``,
    },
    {
        id: "compresor-3",
        dataProducto: "compresor",
        categoria: "compresor",
        nombre: "Compresor de AC",
        img: "img/compresores/compresorAC2para Columbia o century original Alliance1.webp",
        imgHover: "img/compresores/compresorAC2para Columbia o century original Alliance2.webp",
        precio: 0,
        repuesto: "para Columbia o century original Alliance    ", 
        descripcion: ``,
    },
    //----  TRANSMISION -----
    {
        id: "culata-1",
        dataProducto: "culatas",
        categoria: "culatas",
        nombre: "Culata",
        img: "img/culatas/culataDetroitDDEC5-2.webp",
        imgHover: "img/culatas/culataDetroitDDEC5-1.webp",
        precio: 0,
        repuesto: "para motor Detroit 14litros DDEC 5", 
        descripcion: ``,
    },
    {
        id: "deposito-1",
        dataProducto: "culatas",
        categoria: "culatas",
        nombre: "Deposito",
        img: "img/culatas/Deposito de compensacion1.webp",
        imgHover: "img/culatas/Deposito de compensacion2.webp",
        precio: 0,
        repuesto: "de compensacion para Cascadia", 
        descripcion: ``,
    },
    //----  FRENOS
    {
        id: "linkert-1",
        dataProducto: "linkert",
        categoria: "linkert",
        nombre: "linkert-kit",
        img: "img/linkert-kit/linker-kitDDEC4-1.jpg",
        imgHover: "img/linkert-kit/linker-kitDDEC4-2.jpg",
        precio: 0,
        repuesto: "para motor Detroit 12.7 DDEC 4", 
        descripcion: ``,
    },
    {
        id: "linkert-2",
        dataProducto: "linkert",
        categoria: "linkert",
        nombre: "linkert-kit",
        img: "img/linkert-kit/liner-kit-para-motor-ISM.webp",
        imgHover: "img/linkert-kit/liner-kit-para-motor-ISM.webp",
        precio: 0,
        repuesto: "para motor Detroit 14 litros DDEC 5", 
        descripcion: ``,
    },
    //-----   ACCESORIOS    ------
    {
        id: "accesorios-1",
        dataProducto: "aceitera",
        categoria: "accesorios",
        nombre: "Aceitera",
        img: "img/asesorios/aceitera1.webp",
        imgHover: "img/asesorios/aceitera2.webp",
        precio: 0,
        repuesto: "para motor Detroit serie 60 para 12.7 o 14litros original Detroit", 
        descripcion: ``,
    },
    {
        id: "accesorios-1",
        dataProducto: "arnes",
        categoria: "accesorios",
        nombre: "Arnes de potencia",
        img: "img/asesorios/Arnes de inyectores1.webp",
        imgHover: "img/asesorios/Arnes de inyectores2.webp",
        precio: 0,
        repuesto: "DDEC3, DDEC4", 
        descripcion: ``,
    },
    {
        id: "accesorios-2",
        dataProducto: "arnes",
        categoria: "accesorios",
        nombre: "Arnes de sensores",
        img: "img/asesorios/Arnés1.jpg",
        imgHover: "img/asesorios/Arnés2.png",
        precio: 0,
        repuesto: "DDEC3, DDEC4", 
        descripcion: ``,
    },
    {
        id: "accesorios-3",
        dataProducto: "arnes",
        categoria: "accesorios",
        nombre: "Arnes de inyectores",
        img: "img/asesorios/Arnes de inyectores.jpg",
        imgHover: "img/asesorios/Arnes de inyectores3.webp",
        precio: 0,
        repuesto: "DDEC3, DDEC4 y DDEC5", 
        descripcion: ``,
    },
    {
        id: "accesorios-4",
        dataProducto: "arnes",
        categoria: "accesorios",
        nombre: "Arnes de inyectores",
        img: "img/asesorios/arnesdepotenciadetroitDDEC5-1.png",
        imgHover: "img/asesorios/arnesdepotenciadetroitDDEC5-2.png",
        precio: 0,
        repuesto: "para motor 14litros DDEC 5 marca Detroit", 
        descripcion: ``,
    },
    {
        id: "accesorios-5",
        dataProducto: "arnes",
        categoria: "accesorios",
        nombre: "Arnes de inyectores",
        img: "img/asesorios/arnesdepotenciadetroitDDEC5-1.png",
        imgHover: "img/asesorios/arnesdepotenciadetroitDDEC5-2.png",
        precio: 0,
        repuesto: "para motor 14litros DDEC 5 marca Detroit", 
        descripcion: ``,
    },
    {
        id: "accesorios-6",
        dataProducto: "arnes",
        categoria: "accesorios",
        nombre: "Arnes de inyectores",
        img: "img/asesorios/Arnes de inyectores1.webp",
        imgHover: "img/asesorios/Arnes de inyectores2.webp",
        precio: 0,
        repuesto: "para motor Detroit 14 litros DDEC 6", 
        descripcion: ``,
    },
    {
        id: "accesorios-7",
        dataProducto: "arnes",
        categoria: "accesorios",
        nombre: "Arnés",
        img: "img/asesorios/Arnes de potencia1.png",
        imgHover: "img/asesorios/Arnes de potencia1.png",
        precio: 0,
        repuesto: "para motor Detroit M11, N14 o N14", 
        descripcion: ``,
    },
    {
        id: "accesorios-8",
        dataProducto: "base",
        categoria: "accesorios",
        nombre: "Base de bulbos",
        img: "img/asesorios/Basebulbos-1.png",
        imgHover: "img/asesorios/Basebulbos-2.jpg",
        precio: 0,
        repuesto: "para Cascadia", 
        descripcion: ``,
    },
    {
        id: "accesorios-9",
        dataProducto: "biseles",
        categoria: "accesorios",
        nombre: "Biseles",
        img: "img/asesorios/Biseles1.webp",
        imgHover: "img/asesorios/Biseles2.jpg",
        precio: 0,
        repuesto: "Para silvin de columbia", 
        descripcion: ``,
    },
    {
        id: "accesorios-10",
        dataProducto: "bolsa",
        categoria: "accesorios",
        nombre: "Bolsa de suspensión",
        img: "img/asesorios/Bolsa de suspensión1.jpg",
        imgHover: "img/asesorios/Bolsa de suspensión.jpg",
        precio: 0,
        repuesto: "delanter para Columbia o cascadia", 
        descripcion: ``,
    },
    {
        id: "accesorios-11",
        dataProducto: "centro",
        categoria: "accesorios",
        nombre: "Centro de Manifull",
        img: "img/asesorios/Centro de Manifull1.webp",
        imgHover: "img/asesorios/Centro de Manifull2.webp",
        precio: 0,
        repuesto: "de escape para motor 14litros Detroit DDEC 5", 
        descripcion: ``,
    },
    {
        id: "accesorios-12",
        dataProducto: "cilindro",
        categoria: "accesorios",
        nombre: "Cilindro maestro",
        img: "img/asesorios/cilindromaestro1.jpg",
        imgHover: "img/asesorios/cilindromaestro2.jpg",
        precio: 0,
        repuesto: "para Volvo marca TDP", 
        descripcion: ``,
    },
    {
        id: "accesorios-13",
        dataProducto: "computadora",
        categoria: "accesorios",
        nombre: "Computadora",
        img: "img/asesorios/Computadora1.jpg",
        imgHover: "img/asesorios/Computadora2.jpg",
        precio: 0,
        repuesto: "nueva para motor 14litros DDEC 5", 
        descripcion: ``,
    },
    {
        id: "accesorios-14",
        dataProducto: "deposito",
        categoria: "accesorios",
        nombre: "Deposito de compensasion",
        img: "img/asesorios/Deposito de compensasion11.webp",
        imgHover: "img/asesorios/Deposito de compensasion22.webp",
        precio: 0,
        repuesto: "para cascadia marca TDP", 
        descripcion: ``,
    },
    {
        id: "accesorios-15",
        dataProducto: "deposito",
        categoria: "accesorios",
        nombre: "Deposito de compensacion",
        img: "img/asesorios/Deposito de compensasion1.webp",
        imgHover: "img/asesorios/Deposito de compensasion2.webp",
        precio: 0,
        repuesto: "para Columbia o Century", 
        descripcion: ``,
    },
    {
        id: "accesorios-16",
        dataProducto: "enfriadores",
        categoria: "accesorios",
        nombre: "Enfriadores de aceite",
        img: "img/asesorios/Enfriadores de aceite1.jpg",
        imgHover: "img/asesorios/Enfriadores de aceite2.png",
        precio: 0,
        repuesto: "para motores ISX, Detroit, serie 60, Detroit DD15, DD13 marca TDP", 
        descripcion: ``,
    },
    {
        id: "accesorios-17",
        dataProducto: "filtros",
        categoria: "accesorios",
        nombre: "Filtros para cascadia",
        img: "img/asesorios/filtrocascadiaDDC1513-1.jpg",
        imgHover: "img/asesorios/filtrocascadiaDDC1513-2.jpg",
        precio: 0,
        repuesto: "Cascadia motor DD15/DD13", 
        descripcion: ``,
    },
    {
        id: "accesorios-18",
        dataProducto: "filtros",
        categoria: "accesorios",
        nombre: "Filtros originales",
        img: "img/asesorios/filtrocascadiaDDC16-1.webp",
        imgHover: "img/asesorios/filtrocascadiaDDC16-2.webp",
        precio: 0,
        repuesto: "para motor DD15, DD13, DD16 cascadia", 
        descripcion: ``,
    },
    {
        id: "accesorios-19",
        dataProducto: "filtros",
        categoria: "accesorios",
        nombre: "Filtro",
        img: "img/asesorios/filtromotorDetroitDD15DD13-1.jpg",
        imgHover: "img/asesorios/filtromotorDetroitDD15DD13-2.jpg",
        precio: 0,
        repuesto: "origianl para motor Detroit DD15, DD13", 
        descripcion: ``,
    },
    {
        id: "accesorios-20",
        dataProducto: "filtros",
        categoria: "accesorios",
        nombre: "Filtro",
        img: "img/asesorios/filtromotorcascadiaDD13DD15DD16-1.webp",
        imgHover: "img/asesorios/filtromotorcascadiaDD13DD15DD16-2.webp",
        precio: 0,
        repuesto: "filtros originales para motor DD15, DD13, DD16 cascadia", 
        descripcion: ``,
    },
    {
        id: "accesorios-21",
        dataProducto: "fan",
        categoria: "accesorios",
        nombre: "Fan clutch",
        img: "img/asesorios/Fan clutch1.jpg",
        imgHover: "img/asesorios/Fan clutch2.jpg",
        precio: 0,
        repuesto: "Pasta conica marca Horton", 
        descripcion: ``,
    },
    {
        id: "accesorios-22",
        dataProducto: "horqueta",
        categoria: "accesorios",
        nombre: "Horqueta para Clutche",
        img: "img/asesorios/Horqueta para Clutche1.jfif",
        imgHover: "img/asesorios/Horqueta para Clutche1.jfif",
        precio: 0,
        repuesto: "Horqueta para Clutche", 
        descripcion: ``,
    },
    {
        id: "accesorios-23",
        dataProducto: "limpia-brisas",
        categoria: "accesorios",
        nombre: "Limpia brisas",
        img: "img/asesorios/limpiabrisasconmotor1.jpg",
        imgHover: "img/asesorios/limpiabrisasconmotor2.jpg",
        precio: 0,
        repuesto: "armazones con motor de cabezal columbia y cascadia", 
        descripcion: ``,
    },
    {
        id: "accesorios-24",
        dataProducto: "limpia-brisas",
        categoria: "accesorios",
        nombre: "Motor de limpiabrisas",
        img: "img/asesorios/Motor de limpiabrisas1.webp",
        imgHover: "img/asesorios/Motor de limpiabrisas2.webp",
        precio: 0,
        repuesto: "para Freightliner", 
        descripcion: ``,
    },
    {
        id: "accesorios-25",
        dataProducto: "manifull",
        categoria: "accesorios",
        nombre: "Manifull de succion",
        img: "img/asesorios/Manifull de succion1.jpg",
        imgHover: "img/asesorios/Manifull de succion2.jpg",
        precio: 0,
        repuesto: "de succion de aceite para motor Detroit DD15/DD13", 
        descripcion: ``,
    },
    {
        id: "accesorios-26",
        dataProducto: "manifur",
        categoria: "accesorios",
        nombre: "Manifur de escape",
        img: "img/asesorios/Manifull1.jpg",
        imgHover: "img/asesorios/Manifull2.jpg",
        precio: 0,
        repuesto: "para motor Detroit 12.7 DDEC 3, DDEC 4", 
        descripcion: ``,
    },
    {
        id: "accesorios-27",
        dataProducto: "manifull",
        categoria: "accesorios",
        nombre: "Manifull",
        img: "img/asesorios/Manifulldetroit-1.webp",
        imgHover: "img/asesorios/Manifulldetroit-2.webp",
        precio: 0,
        repuesto: "para motor Detroit 12.7", 
        descripcion: ``,
    },
    {
        id: "accesorios-28",
        dataProducto: "retenedor",
        categoria: "accesorios",
        nombre: "Retenedor trasero",
        img: "img/asesorios/Retenedor trasero1.jpg",
        imgHover: "img/asesorios/Retenedor trasero2.png",
        precio: 0,
        repuesto: "para ISX", 
        descripcion: ``,
    },
    {
        id: "accesorios-29",
        dataProducto: "radiador",
        categoria: "accesorios",
        nombre: "Radiador",
        img: "img/asesorios/Radiador1.webp",
        imgHover: "img/asesorios/Radiador2.jpg",
        precio: 0,
        repuesto: "para cascadia, boquillas cruzadas", 
        descripcion: ``,
    },
    {
        id: "accesorios-30",
        dataProducto: "chasis",
        categoria: "accesorios",
        nombre: "SAM de chasis",
        img: "img/asesorios/SAM de chasis1.jpg",
        imgHover: "img/asesorios/SAM de chasis2.jpg",
        precio: 0,
        repuesto: "para Cascadia original Detroit", 
        descripcion: ``,
    },
    {
        id: "accesorios-31",
        dataProducto: "secador",
        categoria: "accesorios",
        nombre: "Secador de aire",
        img: "img/asesorios/Secador de aire1.jpg",
        imgHover: "img/asesorios/Secador de aire2.jfif",
        precio: 0,
        repuesto: "para Cascadia", 
        descripcion: ``,
    },
    {
        id: "accesorios-32",
        dataProducto: "sensores",
        categoria: "accesorios",
        nombre: "Sensores",
        img: "img/asesorios/sensormotordetroit14-1.jpg",
        imgHover: "img/asesorios/sensormotordetroit14-2.jpg",
        precio: 0,
        repuesto: "para motor Detroit 14litros", 
        descripcion: ``,
    },
    {
        id: "accesorios-33",
        dataProducto: "sensores",
        categoria: "accesorios",
        nombre: "Sensores de turbo",
        img: "img/asesorios/Sensores de turbo1.jpg",
        imgHover: "img/asesorios/Sensores de turbo2.jpg",
        precio: 0,
        repuesto: "DDEC 5, DDEC6", 
        descripcion: ``,
    },
    {
        id: "accesorios-34",
        dataProducto: "sensores",
        categoria: "accesorios",
        nombre: "Sensores de presion",
        img: "img/asesorios/Sensores de presion1.jpg",
        imgHover: "img/asesorios/Sensor de presion2.jpg",
        precio: 0,
        repuesto: "de aceite DDEC 5, DDEC 6", 
        descripcion: ``,
    },
    {
        id: "accesorios-35",
        dataProducto: "sensores",
        categoria: "accesorios",
        nombre: "Sensores de tiempo",
        img: "img/asesorios/Sensores de tiempo1.jpg",
        imgHover: "img/asesorios/Sensores de tiempo1.jpg",
        precio: 0,
        repuesto: "levas y cigueñal", 
        descripcion: ``,
    },
    {
        id: "accesorios-36",
        dataProducto: "sensores",
        categoria: "accesorios",
        nombre: "Sensor de presion",
        img: "img/asesorios/Sensor de presion1.jpg",
        imgHover: "img/asesorios/Sensor de presion2.jpg",
        precio: 0,
        repuesto: "de aire para motor ISX", 
        descripcion: ``,
    },
    {
        id: "accesorios-37",
        dataProducto: "starter",
        categoria: "accesorios",
        nombre: "Starter 39MT",
        img: "img/asesorios/Starter 39MT1.jpg",
        imgHover: "img/asesorios/Starter 39MT2.jpg",
        precio: 0,
        repuesto: "para motor 12.7original Freightliner (Alliance)", 
        descripcion: ``,
    },
    {
        id: "accesorios-38",
        dataProducto: "tablero",
        categoria: "accesorios",
        nombre: "Tablero",
        img: "img/asesorios/Tablero1.jpg",
        imgHover: "img/asesorios/Tablero2.jpg",
        precio: 0,
        repuesto: "de indicadores para Freightliner columbia", 
        descripcion: ``,
    },
    {
        id: "accesorios-39",
        dataProducto: "tapones",
        categoria: "accesorios",
        nombre: "Tapones para tamque",
        img: "img/asesorios/Tapones para tamque1.jpg",
        imgHover: "img/asesorios/Tapones para tamque2.webp",
        precio: 0,
        repuesto: "de Freightliner y Kenworth", 
        descripcion: ``,
    },
    {
        id: "accesorios-40",
        dataProducto: "tensores",
        categoria: "accesorios",
        nombre: "Tensor de faja",
        img: "img/asesorios/Tensor de faja1.jpg",
        imgHover: "img/asesorios/Tensor de faja2.webp",
        precio: 0,
        repuesto: "para motor Detroit 12.7 original", 
        descripcion: ``,
    },
    {
        id: "accesorios-41",
        dataProducto: "turbo",
        categoria: "accesorios",
        nombre: "Turbo Garret",
        img: "img/asesorios/Turbo Garret1.jpg",
        imgHover: "img/asesorios/Turbo Garret2.jpg",
        precio: 0,
        repuesto: "para motor Detroit 12.7", 
        descripcion: ``,
    },
    {
        id: "accesorios-42",
        dataProducto: "turbo",
        categoria: "accesorios",
        nombre: "Turbo original",
        img: "img/asesorios/Turbo original1.webp",
        imgHover: "img/asesorios/Turbo original2.webp",
        precio: 0,
        repuesto: "detroit para motor Detroit 14", 
        descripcion: ``,
    },
    //-------   

    //-----     MERCEDEZ-BENZ   ------
    {
        id: "mercedez-1",
        dataProducto: "compresor",
        categoria: "mercedez",
        nombre: "Compresor de aire",
        img: "img/mercedez/compresordeairemercedez1.jpg",
        imgHover: "img/mercedez/compresordeairemercedez2.jpg",
        precio: 0,
        repuesto: "para motor Mercedes OM460 marca TDP", 
        descripcion: ``,
    },
];